# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

GLTR_PROJECT_ID=$(cat /var/run/s6/container_environment/GLTR_PROJECT_ID)
GLTR_PROJECT_NAME=$(cat /var/run/s6/container_environment/GLTR_PROJECT_NAME)
GLTR_VERSION=$(gltr version)

echo
echo " _ _ _ ___| |___ ___ _____ ___   | |_ ___    ___| | |_ ___ "
echo "| | | | -_| |  _| . |     | -_|  |  _| . |  | . | |  _|  _|"
echo "|_____|___|_|___|___|_|_|_|___|  |_| |___|  |_  |_|_| |_|  "
echo "                                            |___|          "
echo
echo "- Workspace for gltr project $GLTR_PROJECT_NAME (id: $GLTR_PROJECT_ID)"
echo "- Container built on Ubuntu 22.04"
echo "- Additional packages added including conda and jupyter as well as gltr tooling"
echo "- $GLTR_VERSION"
echo
echo "let's go!"
echo

